before_install:
  - sudo apt update
  - sudo apt install snapd
  - sudo snap install helm --channel=3.3/stable --classic
script: bash ci/build.sh
branches:
  only:
  - master
  - /^telegraf-operator/release-v\d+\.\d+$/
  - /^telegraf-operator/v\d+\.\d+\.\d+$/
  - /^telegraf-operator/v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/
